### ISSUE TITLE
Location reminder schedule isn't created

### ISSUE THREAD

**Issue by tgamauf** [tgamauf/spritstat#60]

**Comment by tgamauf** [comment]
Also, error message on send:
```
Reverse for 'unsubscribe' with arguments '('i', '02d280edda895fdd6d42299a426488c9e172bc1a')' not found. 2 pattern(s) tried: ['api/v1/sprit/unsubscribe/(?P<uid>[0-9]+)/(?P<token>[-a-zA-Z0-9_]+)/\\Z', 'api/v1/sprit/unsubscribe/\\Z'] : Traceback (most recent call last):
File "/home/app/web/.local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/home/app/web/spritstat/services/notification.py", line 92, in send_location_reminder_notification
_send_mail(LOCATION_REMINDER_TEMPLATE_PREFIX, user, {"location_id": location_id})
File "/home/app/web/spritstat/services/notification.py", line 101, in _send_mail
unsubscribe_url = _get_unsubscribe_url(user)
File "/home/app/web/spritstat/services/notification.py", line 116, in _get_unsubscribe_url
location = reverse("unsubscribe", args=[uid, token])
File "/home/app/web/.local/lib/python3.9/site-packages/django/urls/base.py", line 86, in reverse
return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
File "/home/app/web/.local/lib/python3.9/site-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'unsubscribe' with arguments '('i', '02d280edda895fdd6d42299a426488c9e172bc1a')' not found. 2 pattern(s) tried: ['api/v1/sprit/unsubscribe/(?P<uid>[0-9]+)/(?P<token>[-a-zA-Z0-9_]+)/\\Z', 'api/v1/sprit/unsubscribe/\\Z']
```
