### ISSUE TITLE
Error on price request if station is missing address

### ISSUE THREAD

**Issue by tgamauf** [tgamauf/spritstat#67]
```
Result:
'address' : Traceback (most recent call last):
File "/home/app/web/.local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/home/app/web/spritstat/services/price.py", line 114, in request_location_prices
prices = _request_prices(url)
File "/home/app/web/spritstat/services/price.py", line 140, in _request_prices
result = _parse_prices(item)
File "/home/app/web/spritstat/services/price.py", line 183, in _parse_prices
address = item["location"]["address"]
KeyError: 'address'
```

**Comment by tgamauf** [comment]
Latitude: `48,1080770`
Longitude: `15,8049558 `

**Comment by tgamauf** [comment]
```
[
{
    "id": 1467586,
    "name": "OIL! Tankstelle",
    "location": {
      "address": "Gewerbepark Nord 2 / An Der Autobahnabf. Altlengbach",
      "postalCode": "3052",
      "city": "Innermanzing",
      "latitude": 48.15468,
      "longitude": 15.903307
    },
    "contact": {
      "telephone": "+43  277420579"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "05:00",
        "to": "22:00"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "05:00",
        "to": "22:00"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "05:00",
        "to": "22:00"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "05:00",
        "to": "22:00"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "05:00",
        "to": "22:00"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "07:00",
        "to": "21:00"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "07:00",
        "to": "21:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "07:00",
        "to": "21:00"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": false
    },
    "paymentMethods": {
      "cash": true,
      "debitCard": false,
      "creditCard": true,
      "others": "[ f+f ] card, American Express, Diners, Visa, UTA, MasterCard, Novofleet, V Pay, DKV, Apple Pay, Google Pay, girocard, Bankomat"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": true
    },
    "otherServiceOffers": "Shop, Autowäsche, Backshop, Bistro, Cafe, Vignette, SB-Waschboxen",
    "position": 1,
    "open": true,
    "distance": 8.961025483359474,
    "prices": [
      {
        "fuelType": "DIE",
        "amount": 1.724,
        "label": "Diesel"
      }
    ]
  },
  {
    "id": 33705,
    "name": "AVIA XPress (unser Service: Luft und Wasser)",
    "location": {
      "address": "Laaben 37",
      "postalCode": "3053",
      "city": "Laaben 37",
      "latitude": 48.1028132,
      "longitude": 15.8810816
    },
    "contact": {
      "telephone": "432822501",
      "mail": "office@eigl.at",
      "website": "http://www.eigl.at"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "00:00",
        "to": "24:00"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": true
    },
    "paymentMethods": {
      "cash": false,
      "debitCard": true,
      "creditCard": true,
      "others": "AVIAmat-Tankkarte"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "otherServiceOffers": "LKW-tauglich, Gasthaus",
    "position": 2,
    "open": true,
    "distance": 5.689058694394121,
    "prices": [
      {
        "fuelType": "DIE",
        "amount": 1.729,
        "label": "Diesel"
      }
    ]
  },
  {
    "id": 247877,
    "name": "eni",
    "location": {
      "address": "Tullner Strasse 58",
      "postalCode": "3033",
      "city": "Altlengbach",
      "latitude": 48.1658,
      "longitude": 15.8907
    },
    "contact": {
      "telephone": "0277252573",
      "fax": "02772525734"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "06:30",
        "to": "18:45"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "06:30",
        "to": "18:45"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "06:30",
        "to": "18:45"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "06:30",
        "to": "18:45"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "06:30",
        "to": "18:45"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "08:00",
        "to": "17:30"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "00:00",
        "to": "00:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "00:00",
        "to": "00:00"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": false
    },
    "paymentMethods": {
      "cash": true,
      "debitCard": true,
      "creditCard": true,
      "others": "AMEX,Maestro,Diners Club,DKV,GUTS,MasterCard,Routex,euroShell Card,UTA,VISA"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "position": 3,
    "open": true,
    "distance": 9.047133188133332,
    "prices": [
      {
        "fuelType": "DIE",
        "amount": 1.739,
        "label": "Diesel"
      }
    ]
  },
  {
    "id": 4089,
    "name": "Tankstopp",
    "location": {
      "address": "Hauptstraße 8",
      "postalCode": "3143",
      "city": "Pyhra",
      "latitude": 48.1590154,
      "longitude": 15.6848005
    },
    "contact": {
      "telephone": "43274583083",
      "fax": "43274583084",
      "mail": "office@tankstopp.at",
      "website": "http://www.tankstopp.at"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "06:00",
        "to": "22:00"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "06:00",
        "to": "22:00"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "06:00",
        "to": "22:00"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "06:00",
        "to": "22:00"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "06:00",
        "to": "22:00"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "06:00",
        "to": "22:00"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "07:00",
        "to": "19:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "07:00",
        "to": "19:00"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": false
    },
    "paymentMethods": {
      "cash": true,
      "debitCard": true,
      "creditCard": true,
      "others": "Tankkarte"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "otherServiceOffers": "Stammkundenkartenrabatt 1Cent/Liter",
    "position": 4,
    "open": true,
    "distance": 10.575040967347979,
    "prices": [
      {
        "fuelType": "DIE",
        "amount": 1.766,
        "label": "Diesel"
      }
    ]
  },
  {
    "id": 35664,
    "name": "BP",
    "location": {
      "address": "Hainfelderstr. ",
      "postalCode": "3071",
      "city": "Boeheimkirchen",
      "latitude": 48.194014,
      "longitude": 15.765381
    },
    "contact": {
      "telephone": "4327433265",
      "fax": "432743231220",
      "mail": "tremmel.transporte@aon.at"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "06:00",
        "to": "20:30"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "06:00",
        "to": "20:30"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "06:00",
        "to": "20:30"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "06:00",
        "to": "20:30"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "06:00",
        "to": "20:30"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "06:30",
        "to": "20:30"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "07:00",
        "to": "20:30"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "07:00",
        "to": "20:30"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": false
    },
    "paymentMethods": {
      "cash": true,
      "debitCard": true,
      "creditCard": true,
      "others": "Routex"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "otherServiceOffers": "Autowash, SB-Wash",
    "position": 5,
    "open": true,
    "distance": 10.006196685668433,
    "prices": [
      {
        "fuelType": "DIE",
        "amount": 1.779,
        "label": "Diesel"
      }
    ]
  },
  {
    "id": 33627,
    "name": "AVIA mit Bedienung",
    "location": {
      "postalCode": "3071",
      "city": "Fahrafeld 15",
      "latitude": 48.146059,
      "longitude": 15.749009
    },
    "contact": {
      "telephone": "4327445619",
      "fax": "4327445619",
      "mail": "office@eigl.at"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "07:00",
        "to": "18:00"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "07:00",
        "to": "18:00"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "07:00",
        "to": "18:00"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "07:00",
        "to": "18:00"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "07:00",
        "to": "18:00"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "07:00",
        "to": "13:00"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "07:00",
        "to": "20:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "07:00",
        "to": "20:00"
      }
    ],
    "offerInformation": {
      "service": true,
      "selfService": false,
      "unattended": false
    },
    "paymentMethods": {
      "cash": true,
      "debitCard": false,
      "creditCard": false
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "otherServiceOffers": "Kaufhaus",
    "position": 6,
    "open": true,
    "distance": 5.928912661101826,
    "prices": []
  },
  {
    "id": 1474273,
    "name": "eni",
    "location": {
      "address": "Hauptstrasse 77",
      "postalCode": "3170",
      "city": "Hainfeld",
      "latitude": 48.03805,
      "longitude": 15.76293
    },
    "contact": {
      "telephone": "027642504",
      "fax": "02764250432"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "05:30",
        "to": "21:30"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "05:30",
        "to": "21:30"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "05:30",
        "to": "21:30"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "05:30",
        "to": "21:30"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "05:30",
        "to": "21:30"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "05:30",
        "to": "21:30"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "05:30",
        "to": "21:30"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "05:30",
        "to": "21:30"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": false
    },
    "paymentMethods": {
      "cash": true,
      "debitCard": true,
      "creditCard": true,
      "others": "AMEX,Maestro,Diners Club,DKV,GUTS,LOGP,MasterCard,Routex,euroShell Card,UTA,VISA"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "position": 7,
    "open": true,
    "distance": 8.397506175523434,
    "prices": []
  },
  {
    "id": 1354814,
    "name": "avanti - Hainfeld Wiener Straße 24",
    "location": {
      "address": "Wiener Strasse 24",
      "postalCode": "3170",
      "city": "Hainfeld",
      "latitude": 48.03366,
      "longitude": 15.77878
    },
    "contact": {
      "telephone": "800202055",
      "fax": "800",
      "website": "www.omv.com"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "00:00",
        "to": "24:00"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": true
    },
    "paymentMethods": {
      "cash": false,
      "debitCard": true,
      "creditCard": true,
      "others": "OMV STATIONSKARTE, DKV, MASTERCARD, MAESTRO, ROUTEX, DINERS, VISA"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "position": 8,
    "open": true,
    "distance": 8.508396345325764,
    "prices": []
  },
  {
    "id": 1470707,
    "name": "Tankstelle Dürer",
    "location": {
      "address": "Hauptstraße 66",
      "postalCode": "3052",
      "city": "Neustift- Innermanzing",
      "latitude": 48.138859472689944,
      "longitude": 15.91062878873917
    },
    "contact": {
      "telephone": "06648540579",
      "mail": "duererbagger@gmail.com"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "00:00",
        "to": "24:00"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": false,
      "unattended": true
    },
    "paymentMethods": {
      "cash": false,
      "debitCard": true,
      "creditCard": true
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": false
    },
    "position": 9,
    "open": true,
    "distance": 8.567324483456153,
    "prices": []
  },
  {
    "id": 34347,
    "name": "BICHLER premiumDIESEL XTREMEverde",
    "location": {
      "address": "Bernreit 26",
      "postalCode": "3163",
      "city": "Rohrbach",
      "latitude": 48.0459966,
      "longitude": 15.7235472
    },
    "contact": {
      "telephone": "432764790116",
      "fax": "4327647901316",
      "mail": "koeberl@bichler.at",
      "website": "http://www.bichler.at"
    },
    "openingHours": [
      {
        "day": "MO",
        "label": "Montag",
        "order": 1,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DI",
        "label": "Dienstag",
        "order": 2,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "MI",
        "label": "Mittwoch",
        "order": 3,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "DO",
        "label": "Donnerstag",
        "order": 4,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FR",
        "label": "Freitag",
        "order": 5,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SA",
        "label": "Samstag",
        "order": 6,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "SO",
        "label": "Sonntag",
        "order": 7,
        "from": "00:00",
        "to": "24:00"
      },
      {
        "day": "FE",
        "label": "Feiertag",
        "order": 8,
        "from": "00:00",
        "to": "24:00"
      }
    ],
    "offerInformation": {
      "service": false,
      "selfService": true,
      "unattended": true
    },
    "paymentMethods": {
      "cash": false,
      "debitCard": false,
      "creditCard": false,
      "others": "Bichler Tec Ausweis"
    },
    "paymentArrangements": {
      "cooperative": false,
      "clubCard": true,
      "clubCardText": "Bichler Tec Ausweis"
    },
    "otherServiceOffers": "Premiumdiesel XTREMEverde mit Beimengung von Synthetikdiesel anstatt Biodiesel, Vorteil: keine Algenbildung, geringerer CO2 Ausstoß, kälteunempfindlich, bessere Leistung, Verbrauchsreduktion",
    "position": 10,
    "open": true,
    "distance": 9.187115280232147,
    "prices": []
  }
]
```

**Comment by tgamauf** [comment]
Invalid result example:
```
{
    "id": 33627,
    "name": "AVIA mit Bedienung",
    "location": {
      "postalCode": "3071",
      "city": "Fahrafeld 15",
      "latitude": 48.146059,
      "longitude": 15.749009
    },
…
}
```
