### ISSUE TITLE
Request location prices error: connection refused

### ISSUE THREAD

**Issue by tgamauf** [tgamauf/spritstat#86]
```
HTTPSConnectionPool(host='api.e-control.at', port=443): Max retries exceeded with url: /sprit/1.0/search/gas-stations/by-address?latitude=48.1053722&longitude=16.3089072&fuelType=SUP (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc12f58c940>: Failed to establish a new connection: [Errno 111] Connection refused')) : Traceback (most recent call last):
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
raise err
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
self._validate_conn(conn)
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
conn.connect()
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
conn = self._new_conn()
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc12f58c940>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/app/web/.local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/home/app/web/spritstat/services/price.py", line 114, in request_location_prices
prices = _request_prices(url)
File "/home/app/web/spritstat/services/price.py", line 136, in _request_prices
json_data = _execute_api_request(url)
File "/home/app/web/spritstat/services/price.py", line 154, in _execute_api_request
r = http.request("GET", url)
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/request.py", line 74, in request
return self.request_encode_url(
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/request.py", line 96, in request_encode_url
return self.urlopen(method, url, **extra_kw)
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/poolmanager.py", line 375, in urlopen
response = conn.urlopen(method, u.request_uri, **kw)
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
return self.urlopen(
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
return self.urlopen(
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
return self.urlopen(
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
retries = retries.increment(
File "/home/app/web/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.e-control.at', port=443): Max retries exceeded with url: /sprit/1.0/search/gas-stations/by-address?latitude=48.1053722&longitude=16.3089072&fuelType=SUP (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc12f58c940>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by tgamauf** [comment]
Location id: 146
